dofile(minetest.get_modpath("mobs").."/api.lua")
dofile(minetest.get_modpath("mobs").."/egg.lua")
mobs:register_mob("mobs:monster_lv1", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 8,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_white.png",
	textures = {
		{"mobs_monster_lv1.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv2", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 16,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_pink.png",
	textures = {
		{"mobs_monster_lv2.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv3", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 24,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_yellow.png",
	textures = {
		{"mobs_monster_lv3.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv4", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 32,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_orange.png",
	textures = {
		{"mobs_monster_lv4.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv5", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 40,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_magenta.png",
	textures = {
		{"mobs_monster_lv5.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv6", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 48,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_green.png",
	textures = {
		{"mobs_monster_lv6.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv7", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 56,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_dark_green.png",
	textures = {
		{"mobs_monster_lv7.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv8", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 64,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_cyan.png",
	textures = {
		{"mobs_monster_lv8.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv9", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 72,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_blue.png",
	textures = {
		{"mobs_monster_lv9.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv10", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 80,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_brown.png",
	textures = {
		{"mobs_monster_lv10.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv11", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 88,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_grey.png",
	textures = {
		{"mobs_monster_lv11.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv12", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 96,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_dark_grey.png",
	textures = {
		{"mobs_monster_lv12.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv13", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 104,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_black.png",
	textures = {
		{"mobs_monster_lv13.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv14", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 112,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_red.png",
	textures = {
		{"mobs_monster_lv14.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv15", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 2,
	hp_max = 120,
	armor = 100,
	visual_size = {x=3, y=2.6},
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.x",
    blood_texture = "wool_violet.png",
	textures = {
		{"mobs_monster_lv15.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})
mobs:register_mob("mobs:monster_lv16", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 10,
	hp_max = 200,
	armor = 100,
	visual_size = {x=1, y=1},
	collisionbox = {-0.4, -1.0, -0.4, 0.4, 1.0, 0.4},
	visual = "mesh",
	mesh = "mobs_knight.b3d",
    blood_texture = "",
	textures = {
		{"mobs_monster_lv16.png"},
	},
	makes_footstep_sound = true,
	walk_velocity = 1,
	run_velocity = 2,
	jump = true,
	water_damage = 1,
	lava_damage = 5,
	light_damage = 0,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})